name: C/C++ CI

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure
      run: cmake -DWITH_examples=ON -DWITH_tests=ON -DWITH_demos=ON .

    - name: Build
      run: make  # Replace with your build command
